export const FUN_NAMES = [
  'Kochu Rajan',
  'Goli Master',
  'Last Bench Hero',
  'Ammini Kutty',
  'Kuttan Pilla',
  'Chakka Boss',
  'Mango Thief',
  'Unniyappam',
  'Porotta King',
  'Chaya Kada',
  'Pappadam Pro',
  'Kanji Warrior',
  'Thattukada Star',
  'Monsoon Kid',
  'Coconut Sniper',
  'Tharavadu Don',
  'Puttu Pandit',
  'Banana Chips',
  'Kappa Captain',
  'Meen Curry',
  'Rasam Rocket',
  'Dosa Dynamo',
  'Idli Ace',
  'Vada Vikram',
  'Payasam Prince',
  'Laddoo Legend',
  'Jalebi Jet',
  'Samosa Sultan',
  'Chalk Piece',
  'Tuition Topper',
  'Bench Drummer',
  'Recess Raja',
  'PT Period',
  'Cycle Kutty',
  'Kite Runner',
  'Rain Holiday',
  'Mittai Kada',
  'Appu Kuttan',
  'Thumbi Rani',
  'Goli Guru',
  'Marble Mani',
  'Pazhampori',
] as const;

export function randomName(rng: () => number = Math.random): string {
  return FUN_NAMES[Math.floor(rng() * FUN_NAMES.length)];
}
